# См. статью по ссылке https://aka.ms/customizecontainer, чтобы узнать как настроить контейнер отладки и как Visual Studio использует этот Dockerfile для создания образов для ускорения отладки.

# Этот этап используется при запуске из VS в быстром режиме (по умолчанию для конфигурации отладки)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# Этот этап используется для сборки проекта службы
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ServiceCollectionsExtensions/ServiceCollectionsExtensions.csproj", "ServiceCollectionsExtensions/"]
RUN dotnet restore "./ServiceCollectionsExtensions/ServiceCollectionsExtensions.csproj"
COPY . .
WORKDIR "/src/ServiceCollectionsExtensions"
RUN dotnet build "./ServiceCollectionsExtensions.csproj" -c $BUILD_CONFIGURATION -o /app/build

COPY ["ShopServices.Abstractions/ShopServices.Abstractions.csproj", "ShopServices.Abstractions/"]
RUN dotnet restore "./ShopServices.Abstractions/ShopServices.Abstractions.csproj"
COPY . .
WORKDIR "/src/ShopServices.Abstractions"
RUN dotnet build "./ShopServices.Abstractions.csproj" -c $BUILD_CONFIGURATION -o /app/build

COPY ["ShopServices.BusinessLogic/ShopServices.BusinessLogic.csproj", "ShopServices.BusinessLogic/"]
RUN dotnet restore "./ShopServices.BusinessLogic/ShopServices.BusinessLogic.csproj"
COPY . .
WORKDIR "/src/ShopServices.BusinessLogic"
RUN dotnet build "./ShopServices.BusinessLogic.csproj" -c $BUILD_CONFIGURATION -o /app/build

COPY ["ShopServices.Core/ShopServices.Core.csproj", "ShopServices.Core/"]
RUN dotnet restore "./ShopServices.Core/ShopServices.Core.csproj"
COPY . .
WORKDIR "/src/ShopServices.Core"
RUN dotnet build "./ShopServices.Core.csproj" -c $BUILD_CONFIGURATION -o /app/build

COPY ["ShopServices.DataAccess/ShopServices.DataAccess.csproj", "ShopServices.DataAccess/"]
RUN dotnet restore "./ShopServices.DataAccess/ShopServices.DataAccess.csproj"
COPY . .
WORKDIR "/src/ShopServices.DataAccess"
RUN dotnet build "./ShopServices.DataAccess.csproj" -c $BUILD_CONFIGURATION -o /app/build


COPY ["Employees.API/Employees.API.csproj", "Employees.API/"]
RUN dotnet restore "./Employees.API/Employees.API.csproj"
COPY . .
WORKDIR "/src/Employees.API"
RUN dotnet build "./Employees.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Этот этап используется для публикации проекта службы, который будет скопирован на последний этап
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Employees.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Этот этап используется в рабочей среде или при запуске из VS в обычном режиме (по умолчанию, когда конфигурация отладки не используется)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Employees.API.dll"]