namespace ShopServices.Core
{
    public static class ResultMessager
    {
        public static string OK = "OK";
        public static string NOT_FOUND = "Not found";

        //AuthUser
        public const string EMPTY_OR_NULL_PASSWORD_HASH = "Empty/null/space password hash";
        public const string GRANTER_NOT_FOUND = "granter not found";
        public const string USER_NOT_FOUND = "User not found";
        public const string PASSWORD_HASH_MISMATCH = "Password(hash) mismatch";
        public const string USER_UPDATED = "User updated";
        public const string USER_IS_ACTUAL = "User is actual";
        public const string LOGIN_MISMATCH = "Login mismatch";
        public const string GRANTERLOGIN_MISMATCH = "GranterLogin mismatch";

        public const string EMPLOYEE_PARAM_NAME = "employee";
        public const string USER_ID_SHOULD_BE_ZERO = "Id in Register request should be zero (generated by DB)";
        public const string LOGIN_SHOULD_NOT_BE_EMPTY = "Login should be not empty";
        public const string NAME_SHOULD_NOT_BE_EMPTY = "Name should be not empty";
        public const string SURNAME_SHOULD_NOT_BE_EMPTY = "Surname should be not empty";
        public const string EMAIL_SHOULD_NOT_BE_EMPTY = "Email should be not empty";
        public const string PASSWORD_HASH_SHOULD_NOT_BE_EMPTY = "Passwordhash should be not empty";
        public const string LOGINDATA_PARAM_NAME = "loginData";
        public const string GRANTROLEDATA_PARAM_NAME = "grantRoleData";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY = "GranterLogin should be not empty";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY_DELETE = "GranterLogin should be not empty when GranterId is not null";
        public const string GRANTERLOGIN_SHOULD_BE_EMPTY_DELETE = "GranterLogin should be empty when GranterId is null";
        public const string UPDATEACCOUNTDATA_PARAM_NAME = "updateAccountData";
        public const string DELETEACCOUNTDATA_PARAM_NAME = "deleteAccountData";
        public const string CONFLICT = "Conflict with existing AuthUser";
        public const string ALREADY_EXISTS = "AuthUser is already existing";
    }
}
