namespace ShopServices.Core
{
    public static class ResultMessager
    {
        public static string OK = "OK";
        public static string NOT_FOUND = "Not found";

        //Employee
        public const string EMPTY_OR_NULL_PASSWORD_HASH = "Empty/null/space password hash";
        public const string GRANTER_NOT_FOUND = "granter not found";
        public const string USER_NOT_FOUND = "User not found";
        public const string PASSWORD_HASH_MISMATCH = "Password(hash) mismatch";
        public const string USER_UPDATED = "User updated";
        public const string USER_IS_ACTUAL = "User is actual";
        public const string LOGIN_MISMATCH = "Login mismatch";
        public const string GRANTERLOGIN_MISMATCH = "GranterLogin mismatch";

        public const string EMPLOYEE_PARAM_NAME = "employee";
        public const string USER_ID_SHOULD_BE_ZERO = "Id in Register request should be zero (generated by DB)";
        public const string LOGIN_SHOULD_NOT_BE_EMPTY = "Login should be not empty";
        public const string NAME_SHOULD_NOT_BE_EMPTY = "Name should be not empty";
        public const string SURNAME_SHOULD_NOT_BE_EMPTY = "Surname should be not empty";
		public const string ADDRESS_SHOULD_NOT_BE_EMPTY = "Address should be not empty";
		public const string EMAIL_SHOULD_NOT_BE_EMPTY = "Email should be not empty";
        public const string PASSWORD_HASH_SHOULD_NOT_BE_EMPTY = "Passwordhash should be not empty";
        public const string LOGINDATA_PARAM_NAME = "loginData";
        public const string GRANTROLEDATA_PARAM_NAME = "grantRoleData";
        public const string CHANGEDISCOUNTGROUPSDATA_PARAM_NAME = "changeDiscountGroupsData";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY = "GranterLogin should be not empty";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY_DELETE = "GranterLogin should be not empty when GranterId is not null";
        public const string GRANTERLOGIN_SHOULD_BE_EMPTY_DELETE = "GranterLogin should be empty when GranterId is null";
        public const string UPDATEACCOUNTDATA_PARAM_NAME = "updateAccountData";
        public const string DELETEACCOUNTDATA_PARAM_NAME = "deleteAccountData";
        public const string CONFLICT = "Conflict with existing entity";
        public const string ALREADY_EXISTS = "Entity is already existing and is actual";

        public const string UPDATECOURIERREQUEST_PARAM_NAME = "updateCourierRequest";
        public const string TRANSPORT_FIELD_SHOULD_NOT_BE_EMPTY = "Transport field should be not empty";
        public const string AREAS_FIELD_SHOULD_NOT_BE_EMPTY = "Areas field should be not empty";
        public const string DELIVERYTIMESCHEDULE_FIELD_SHOULD_NOT_BE_EMPTY = "DeliveryTimeSchedule field should be not empty";

        public const string EMPLOYEE_IS_NOT_COURIER = "Employee is not courier";
        public const string EMPLOYEE_IS_NOT_MANAGER = "Employee is not manager";

        //categories
        public const string CATEGORY_RARAM_NAME = "category";
        public const string NEWCATEGORY_RARAM_NAME = "newCategory";
        public const string CATEGORY_UPDATED = "Category updated";
        public const string CATEGORY_IS_ACTUAL = "Category is actual";

        //products
        public const string NEWPRODUCT_RARAM_NAME = "newProduct";
        public const string PRODUCT_RARAM_NAME = "product";
        public const string ARTICLENUMBER_SHOULD_NOT_BE_EMPTY = "ArticleNumber should be not empty";
        public const string BRAND_SHOULD_NOT_BE_EMPTY = "Brand should be not empty";
        public const string DIMENSIONS_SHOULD_NOT_BE_EMPTY = "Dimensions should be not empty";
        public const string GOODGROUPS_SHOULD_NOT_BE_NULL_OR_EMPTY = "GoodsGroups should not be null or empty";
        public const string PARAMS_SHOULD_NOT_BE_EMPTY = "Params should be not empty";
        public const string IMAGEURL_SHOULD_NOT_BE_EMPTY = "ImageUrl should be not empty";
        public const string URL_SHOULD_NOT_BE_EMPTY = "Url should be not empty";
        public const string PRODUCT_UPDATED = "Product updated";
        public const string PRODUCT_IS_ACTUAL = "Product is actual";
        public const string PRODUCT_NOT_FOUND = "Product not found";

        public const string PRICEPERUNIT_SHOULD_BE_NULL_OR_POSITIVE = "PricePerUnit should be null or positive";

        //prices
        public const string PRICE_NOT_FOUND = "Price not found";
        public const string PRICE_FOR_OTHER_PRODUCT_ID = "Price for other product id";
        public const string PRICE_PER_UNIT_MISMATCH = "PricePerUnit mismatch";
        public const string PRICEPERUNIT_SHOULD_BE_POSITIVE = "PricePerUnit should be positive";
        public const string CURRENCY_SHOULD_NOT_BE_EMPTY = "Currency should be not empty";
        public const string UNIT_SHOULD_NOT_BE_EMPTY = "Unit should be not empty";
        public const string ACTUALFROMDT_SHOULD_BE_GE_NOW = "ActualFromDt should be >= current time";
        public const string ACTUALTODT_SHOULD_BE_GE_NOW = "ActualToDt should be >= current time";
        public const string ACTUALFROMDT_SHOULD_BE_LESS_THAN_ACTUALTODT = "ActualFromDt should < ActualToDt";
        public const string NEWPRICE_RARAM_NAME = "newPrice";
        public const string ACTUALTODT_UPDATED = "ActualToDt updated";
        public const string ACTUALTODT_IS_ACTUAL = "ActualToDt is actual";
        
        //orders
        public const string ORDER_RARAM_NAME = "order";
        public const string PRICE_SHOULD_BE_POSITIVE = "Price should be positive";
        public const string QUANTITY_SHOULD_BE_POSITIVE = "Quantity should be positive";
        public const string COST_SHOULD_BE_POSITIVE = "Cost should be positive";
        public const string ORDER_POSITIONS_MUST_BE_NOT_NULL = "order.Positions must be not null";
        public const string ORDER_POSITIONS_MUST_HAVE_POSITION = "order.Positions must have 1 or more position(s)";
        public const string PRODUCT_IS_ARCHIEVED = "Product is archived, not available to order";
        public const string PRICE_ID_IS_NULL = "product.PriceId == null, not available to order";
        public const string PRICE_PER_UNIT_IS_NULL = "product.PricePerUnit == null, not available to order";
        public const string BUYER_NOT_FOUND = "Buyer not found";
        public const string POSITION_CURRENCY_IS_NOT_PRICE_CURRENCY = "OrderPosition.Currency != Price.Currency";
        public const string ORDER_CURRENCY_IS_NOT_PRICE_CURRENCY = "Order.Currency != Price.Currency";
        public const string POSITION_PRICE_IS_LESS_THAN_DISCOUNT_PRICEPERUNIT = "OrderPosition.Price < DiscountPricePerUnit";
        public const string PRICE_PRICEPERUNIT_IS_NOT_EQUAL_PRODUCT_PRICEPERUNIT = "Price.PricePerUnit != Product.PricePerUnit";
        public const string PRICE_ACTUAL_TO_DT_IS_NOT_ACTUAL = "Price.ActualToDt is not actual (outdated) (price.ActualToDt < Now), not available to order";
        public const string PRICE_ACTUAL_FROM_DT_IS_NOT_ACTUAL = "Price.ActualFromDt is not actual (Now < price.ActualFromDt), not available to order";
        public const string BUYER_ID_IS_NOT_ORDER_BUYER_ID = "buyer.Id != order.BuyerId";
        public const string BUYER_ID_IS_NOT_BUYER_ID = "buyer.Id != Buyer.Id";
        public const string BUYER_ID_FROM_CLAIM_IS_NOT_FROM_REQUEST = "buyerIdFromClaim != buyerIdFromRequest";
        public const string BUYER_LOGIN_IS_NOT_ORDER_BUYER_LOGIN = "buyer.Login != order.Buyer.Login";
        public const string BUYER_EMAIL_IS_NOT_ORDER_BUYER_EMAIL = "buyer.Email != order.Buyer.Email";
        public const string ORDER_BUYER = "order.Buyer";
        public const string PRODUCT_ID_MISMATCH = "ProductId mismatch";
        public const string COST_MISMATCH_MORE_THAN_PERMISSIBLE_PRICE_ERROR = "Cost mismatch more then permissible price error";
        public const string BUYER_IS_BLOCKED = "Buyer is blocked";
        public const string PAYMENT_INFO_SHOULD_NOT_BE_EMPTY = "PaymentInfo should be not empty";
        public const string DELIVERY_ADDRESS_SHOULD_NOT_BE_EMPTY = "DeliveryAddress should be not empty";
        public const string EXTRA_INFO_SHOULD_NOT_BE_EMPTY = "ExtraInfo should be not empty";
        public const string IMPOSSIBLE_TO_ADD_ARCHIVED_ORDER = "Impossible to add archived order";
        public const string TIME_DESYNCHRONIZATION_MORE_THAN_PERMISSIBLE_TIME_DESYNC_SECONDS = "Time desynchronization more than permissible time desynchronization limit";
        public const string PLANNEDDELIVERYTIME_IS_LESS_THEN_NOW = "PlannedDeliveryTime is less then now";
        public const string ORDER_ID_SHOULD_BE_POSITIVE = "orderId should be positive (>0)";
        public const string CONFIRMATION_STRING_SHOULD_BE_NOT_NULL_OR_EMPTY = "confirmationString should be not null/empty";
        public const string EXTRA_INFO_SHOULD_BE_NOT_NULL_OR_EMPTY = "extraInfo should be not null/empty";
        public const string MANAGER_ID_IS_NULL = "managerId is null, should be positive (>0)";
        public const string MANAGER_ID_IS_ZERO = "managerId is 0, should be positive (>0) or null";
        public const string COURIER_ID_IS_ZERO = "courierId is 0, should be positive (>0) or null";
        public const string PLANNED_DELIVERY_TIME_SHOULD_BE_MORE_THAN_NOW = "plannedDeliveryTime should be > Now";
        public const string ORDER_NOT_FOUND = "Order not found";
        public const string OTHER_BUYERS_ORDER = "Other buyer's order";
        public const string CONFIRMATION_STRING_MISMATCH = "confirmationString mismatch";
        public const string ORDER_CANCELED = "Order canceled";
        public const string ORDER_CANCELED_EARLIER = "Order canceled earlier";
        public const string ORDER_CONFIRMED = "Order confirmed";
        public const string ORDER_CONFIRMED_EARLIER = "Order confirmed earlier";
        public const string ORDER_RECEIVED_EARLIER = "Order received earlier";
        public const string ORDER_DELIVERED_EARLIER = "Order delivered earlier";
        public const string ORDER_CANCELED_EARLIER_DELIVERED_TO_SHOP = "Order canceled earlier, but delivered to shop";
        public const string ERROR_ORDER_CANCELED_EARLIER_OR_RECEIVED = "ERROR: Order canceled earlier OR received";
        public const string ORDER_IS_ACTUAL = "Order is actual";
        public const string ERROR_ORDER_CANCELED_EARLIER_OR_DELIVERED = "ERROR: Order canceled earlier OR delivered";
        public const string COURIER_ID_IS_NULL = "courier is null, expected positive (>0)";

        //shops
        public const string SHOP_ID_SHOULD_BE_POSITIVE = "shop.Id == 0, should be positive (>0)";
        public const string SHOP_NOT_FOUND = "shop (shopId) not found";
        public const string COURIER_ID_MISMATCH = "courierId mismatch";
        public const string MANAGER_ID_MISMATCH = "managerId mismatch";
        public const string BUYER_ID_MISMATCH = "buyerId mismatch";
        public const string NEW_SHOP_RARAM_NAME = "newShop";
        public const string SHOP_RARAM_NAME = "shop";
        public const string PHONE_SHOULD_NOT_BE_EMPTY = "Phone should be not empty";
        public const string WORK_SCHEDULE_SHOULD_NOT_BE_EMPTY = "WorkSchedule should be not empty";
        public const string SHOP_IS_ACTUAL = "Shop is actual";
        public const string SHOP_UPDATED = "Shop updated";

        //warehouses
        public const string NEW_WAREHOUSE_RARAM_NAME = "newWarehouse";
        public const string WAREHOUSE_ID_SHOULD_BE_POSITIVE = "warehouse.Id == 0, should be positive (>0)";
        public const string WAREHOUSE_RARAM_NAME = "warehouse";
        public const string WAREHOUSE_IS_ACTUAL = "Warehouse is actual";
        public const string WAREHOUSE_UPDATED = "Warehouse updated";
        public const string WAREHOUSE_NOT_FOUND = "warehouse (WarehouseId) not found";
        
        //deliveries
        public const string DELIVERY_RARAM_NAME = "delivery";
        public const string MASS_IN_GRAMS_SHOULD_BE_POSITIVE = "delivery.MassInGrams should be positive";
        public const string COMMENT_SHOULD_NOT_BE_EMPTY = "Comment should not be empty";
        public const string DELIVERY_ID_SHOULD_BE_POSITIVE = "delivery.Id == 0, should be positive";
        public const string DELIVERY_STATUS_SHOULD_BE_TOADD = "delivery.Status should be ToAdd";
        public const string REGIONCODE_SHOULD_BE_POSITIVE = "delivery.RegionCode == 0, should be positive";
        public const string DELIVERY_UPDATED = "Delivery updated";
        public const string DELIVERY_IS_ACTUAL = "Delivery is actual";

        //NOTIFICATIONS
        public const string NOTIFICATION_RARAM_NAME = "notification";
        public const string NOTIFICATION_ID_SHOULD_BE_POSITIVE = "notification.Id == 0, should be positive (>0)";
        public const string NOTIFICATION_SENDER_SHOULD_NOT_BE_EMPTY = "notification.Sender(From) should be not empty";
        public const string NOTIFICATION_RECIPIENT_SHOULD_NOT_BE_EMPTY = "notification.Recipient(To) should be not empty";
        public const string NOTIFICATION_MESSAGE_SHOULD_NOT_BE_EMPTY = "notification.Message should be not empty";
        public const string NOTIFICATION_TOPIC_SHOULD_NOT_BE_EMPTY = "notification.Topic should be not empty";
        public const string NOTIFICATION_CREATOR_SHOULD_NOT_BE_EMPTY = "notification.Creator should be not empty";
        public const string CHANGED_ENTITY_ID_SHOULD_BE_POSITIVE = "notification.ChangedEntityId == 0, should be positive (>0)";
        public const string NOTIFICATION_CREATED_IN_FUTURE = "notification.Created > Now"; 
        public const string NOTIFICATION_SENT_SHOULD_BE_NULL = "notification.Sent != null, should be null to AddNotification";
        public const string NOTIFICATION_LAST_ATTEMPT_SHOULD_BE_NULL = "notification.LastUnsuccessfulAttempt != null, should be null to AddNotification";
        public const string NOTIFICATION_UNSUCCESSFUL_ATTEMPTS_SHOULD_BE_ZERO = "notification.UnsuccessfulAttempts != 0, should be 0 to AddNotification";
        public const string EMAIL_NOTIFICATION_SENT_EARLIER = "Email notification sent earlier";
        public const string PHONE_NOTIFICATION_SENT_EARLIER = "Phone notification sent earlier";
        public const string UNSUCCESSFULL_ATTEMPT_SAVED_EARLIER = "Unsuccessful attempt saved earlier";
        public const string SENDRESULT_IS_NULL_TELEGRAM = "sendResult == null at telegram notification";
        public const string SENDRESULT_IS_NULL_EMAIL = "sendResult == null at E-mail notification";
        public const string SENDRESULT_IS_NULL_SMS = "sendResult == null at SMS notification";
        public const string SEND_EMAIL_ERROR = "SendEmail error";
        public const string SEND_SMS_ERROR = "SendSmsNotification error";
        public const string SMS_OK_SIMULATION = "OK simulation. Payed SMS are not implemented in pet project";

        //availabilities
        public const string NEWAVAILABILITY_RARAM_NAME = "newAvailability";
        public const string AVAILABILITY_RARAM_NAME = "availability";
        public const string ID_SHOULD_BE_ZERO = "Availability.Id should be zero";
        public const string PLACENAME_SHOULD_NOT_BE_EMPTY = "PlaceName should be not empty";
        public const string PRODUCT_ID_SHOULD_BE_POSITIVE = "ProductId should be positive";
        public const string SHOP_ID_XOR_WAREHOUSE_ID_SHOULD_BE_POSITIVE = "ShopId XOR WarehouseId should be positive";
        public const string SHOPID_SHOULD_BE_POSITIVE = "shopId == 0, should be positive (>0) or null";
        public const string WAREHOUSEID_SHOULD_BE_POSITIVE = "warehouseId == 0, should be positive (>0) or null";
        public const string CREATED_IS_MORE_THAN_NOW = "Created > Now";
        public const string UPDATED_IS_MORE_THAN_NOW = "Updated > Now";
        public const string LASTSUPPLYTIME_IS_MORE_THAN_NOW = "LastSupplyTime > Now";

        public const string AVAILABILITY_UPDATED = "Availability updated";
        public const string AVAILABILITY_IS_ACTUAL = "Availability is actual";

        //trade
        public const string AMOUNT_SHOULD_BE_POSITIVE = "Amount should be positive (>0)";
        public const string BUYERID_CONFLICT = "buyerId conflict";
        public const string IMPOSSIBLE_TO_ADD_ARCHIVED_PAYMENT = "Impossible to add archived payment";
        public const string REFUNDAMOUNT_SHOULD_BE_POSITIVE = "RefundAmount should be positive (>0)";
        public const string TRADE_RARAM_NAME = "trade";
    }
}
