namespace ShopServices.Core
{
    public static class ResultMessager
    {
        public static string OK = "OK";
        public static string NOT_FOUND = "Not found";

        //Employee
        public const string EMPTY_OR_NULL_PASSWORD_HASH = "Empty/null/space password hash";
        public const string GRANTER_NOT_FOUND = "granter not found";
        public const string USER_NOT_FOUND = "User not found";
        public const string PASSWORD_HASH_MISMATCH = "Password(hash) mismatch";
        public const string USER_UPDATED = "User updated";
        public const string USER_IS_ACTUAL = "User is actual";
        public const string LOGIN_MISMATCH = "Login mismatch";
        public const string GRANTERLOGIN_MISMATCH = "GranterLogin mismatch";

        public const string EMPLOYEE_PARAM_NAME = "employee";
        public const string USER_ID_SHOULD_BE_ZERO = "Id in Register request should be zero (generated by DB)";
        public const string LOGIN_SHOULD_NOT_BE_EMPTY = "Login should be not empty";
        public const string NAME_SHOULD_NOT_BE_EMPTY = "Name should be not empty";
        public const string SURNAME_SHOULD_NOT_BE_EMPTY = "Surname should be not empty";
		public const string ADDRESS_SHOULD_NOT_BE_EMPTY = "Address should be not empty";
		public const string EMAIL_SHOULD_NOT_BE_EMPTY = "Email should be not empty";
        public const string PASSWORD_HASH_SHOULD_NOT_BE_EMPTY = "Passwordhash should be not empty";
        public const string LOGINDATA_PARAM_NAME = "loginData";
        public const string GRANTROLEDATA_PARAM_NAME = "grantRoleData";
        public const string CHANGEDISCOUNTGROUPSDATA_PARAM_NAME = "changeDiscountGroupsData";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY = "GranterLogin should be not empty";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY_DELETE = "GranterLogin should be not empty when GranterId is not null";
        public const string GRANTERLOGIN_SHOULD_BE_EMPTY_DELETE = "GranterLogin should be empty when GranterId is null";
        public const string UPDATEACCOUNTDATA_PARAM_NAME = "updateAccountData";
        public const string DELETEACCOUNTDATA_PARAM_NAME = "deleteAccountData";
        public const string CONFLICT = "Conflict with existing entity";
        public const string ALREADY_EXISTS = "Entity is already existing and is actual";

        public const string UPDATECOURIERREQUEST_PARAM_NAME = "updateCourierRequest";
        public const string TRANSPORT_FIELD_SHOULD_NOT_BE_EMPTY = "Transport field should be not empty";
        public const string AREAS_FIELD_SHOULD_NOT_BE_EMPTY = "Areas field should be not empty";
        public const string DELIVERYTIMESCHEDULE_FIELD_SHOULD_NOT_BE_EMPTY = "DeliveryTimeSchedule field should be not empty";

        public const string EMPLOYEE_IS_NOT_COURIER = "Employee is not courier";
        public const string EMPLOYEE_IS_NOT_MANAGER = "Employee is not manager";

        //categories
        public const string CATEGORY_RARAM_NAME = "category";
        public const string NEWCATEGORY_RARAM_NAME = "newCategory";
        public const string CATEGORY_UPDATED = "Category updated";
        public const string CATEGORY_IS_ACTUAL = "Category is actual";

        //products
        public const string NEWPRODUCT_RARAM_NAME = "newProduct";
        public const string PRODUCT_RARAM_NAME = "product";
        public const string ARTICLENUMBER_SHOULD_NOT_BE_EMPTY = "ArticleNumber should be not empty";
        public const string BRAND_SHOULD_NOT_BE_EMPTY = "Brand should be not empty";
        public const string DIMENSIONS_SHOULD_NOT_BE_EMPTY = "Dimensions should be not empty";
        public const string GOODGROUPS_SHOULD_NOT_BE_NULL_OR_EMPTY = "GoodsGroups should not be null or empty";
        public const string PARAMS_SHOULD_NOT_BE_EMPTY = "Params should be not empty";
        public const string IMAGEURL_SHOULD_NOT_BE_EMPTY = "ImageUrl should be not empty";
        public const string URL_SHOULD_NOT_BE_EMPTY = "Url should be not empty";
        public const string PRODUCT_UPDATED = "Product updated";
        public const string PRODUCT_IS_ACTUAL = "Product is actual";
        public const string PRODUCT_NOT_FOUND = "Product not found";

        public const string PRICEPERUNIT_SHOULD_BE_NULL_OR_POSITIVE = "PricePerUnit should be null or positive";

        //prices
        public const string PRICE_NOT_FOUND = "Price not found";
        public const string PRICE_FOR_OTHER_PRODUCT_ID = "Price for other product id";
        public const string PRICE_PER_UNIT_MISMATCH = "PricePerUnit mismatch";
        public const string PRICEPERUNIT_SHOULD_BE_POSITIVE = "PricePerUnit should be positive";
        public const string CURRENCY_SHOULD_NOT_BE_EMPTY = "Currency should be not empty";
        public const string UNIT_SHOULD_NOT_BE_EMPTY = "Unit should be not empty";
        public const string ACTUALFROMDT_SHOULD_BE_GE_NOW = "ActualFromDt should be >= current time";
        public const string ACTUALTODT_SHOULD_BE_GE_NOW = "ActualToDt should be >= current time";
        public const string ACTUALFROMDT_SHOULD_BE_LESS_THAN_ACTUALTODT = "ActualFromDt should < ActualToDt";
        public const string NEWPRICE_RARAM_NAME = "newPrice";
        public const string ACTUALTODT_UPDATED = "ActualToDt updated";
        public const string ACTUALTODT_IS_ACTUAL = "ActualToDt is actual";
    }
}
