namespace ProjectTasksTrackService.BusinessLogic
{
    public class ErrorStrings
    {
        public const string PROJECT_PARAM_NAME = "project";
        public const string PROJECTS_PARAM_NAME = "projects";
        //public const string PROJECT_IS_NULL = "project is null";
        public const string PROJECT_NULL_ERROR = "Value cannot be null. (Parameter 'project')";
        public const string PROJECT_ID_SHOULD_BE_ZERO = "Project id in Create request should be zero (generated by DB)";
        public const string PROJECT_CODE_SHOULD_NOT_BE_EMPTY = "Project code should be not empty";
        public const string PROJECT_NAME_SHOULD_NOT_BE_EMPTY = "Project name should be not empty";
        public const string PROJECTS_LIST_TO_IMPORT_SHOULD_NOT_BE_NULL = "Projects list to import should not be null";
        public const string PROJECTS_LIST_TO_IMPORT_SHOULD_BE_FILLED = "Projects list to import should contain at least 1 project";
        public const string TASK_NAME_SHOULD_NOT_BE_EMPTY = "Task name should be not empty";
        public const string GET_PROJECT_CALLED_WITH_NULL_EMPTY_PRMS = "GetProject called with null/empty params";
        public const string PROJECT_CONFLICTS = "Project conflict(s)";
        public const string ALREADY_IMPORTED = "Already imported";
        public const string IMPORTED = "Imported";

        public const string SUBPROJECT_PARAM_NAME = "subproject";
        public const string SUBS_PARAM_NAME = "subs";
        //public const string SUBPROJECT_IS_NULL = "subproject is null";
        public const string SUBPROJECT_NULL_ERROR = "Value cannot be null. (Parameter 'subproject')";
        public const string SUBPROJECTS_LIST_TO_IMPORT_SHOULD_NOT_BE_NULL = "ProjectSubDivisions list to import should not be null";
        public const string SUBPROJECTS_LIST_TO_IMPORT_SHOULD_BE_FILLED = "ProjectSubDivisions list to import should contain at least 1 subproject";
        public const string SUBPROJECTS_CONFLICTS = "ProjectSubDivisions conflict(s)";
        public const string SUBPROJECT_CODE_SHOULD_NOT_BE_EMPTY = "ProjectSubDivision code should be not empty";
        public const string SUBPROJECT_NAME_SHOULD_NOT_BE_EMPTY = "ProjectSubDivision name should be not empty";
        public const string SUBPROJECT_ID_SHOULD_BE_ZERO = "ProjectSubDivision id in Create request should be zero (generated by DB)";

        public const string TASK_PARAM_NAME = "task";
        public const string TASKS_PARAM_NAME = "tasks";
        //public const string TASK_IS_NULL = "task is null";
        public const string TASK_NULL_ERROR = "Value cannot be null. (Parameter 'task')";
        public const string TASK_ID_SHOULD_BE_ZERO = "Task id in Create request should be zero (generated by DB)";
        public const string TASK_CODE_SHOULD_BE_EMPTY_IN_CREATE = "Task code in Create request should be null/empty (generated by DB)";
        public const string TASK_CODE_SHOULD_NOT_BE_EMPTY = "Task code should be not empty";
        public const string TASK_CODE_SHOULD_BE_THE_SAME = "Task code should be the same (generated by DB)";
        public const string TASKS_LIST_TO_IMPORT_SHOULD_NOT_BE_NULL = "Tasks list to import should not be null";
        public const string TASKS_LIST_TO_IMPORT_SHOULD_BE_FILLED = "Tasks list to import should contain at least 1 task";
        public const string TASKS_CONFLICTS = "Tasks conflict(s)";

        public const string IMPORT_RESULT_STATUS_CODE_IS_NOT_OK = "importResult.StatusCode != OK";
    }
}
