namespace ProjectTasksTrackService.BusinessLogic
{
    public class ErrorStrings
    {
        public const string PROJECT_ID_SHOULD_BE_ZERO = "Project id in Create request should be zero (generated by DB)";
        public const string PROJECT_CODE_SHOULD_NOT_BE_EMPTY = "Project code should be not empty";
        public const string PROJECT_NAME_SHOULD_NOT_BE_EMPTY = "Project name should be not empty";
        public const string PROJECTS_LIST_TO_IMPORT_SHOULD_NOT_BE_NULL = "Projects list to import should not be null";
        public const string PROJECTS_LIST_TO_IMPORT_SHOULD_BE_FILLED = "Projects list to import should contain at least 1 project";
        public const string TASK_NAME_SHOULD_NOT_BE_EMPTY = "Task name should be not empty";
        public const string GET_PROJECT_CALLED_WITH_NULL_EMPTY_PRMS = "GetProject called with null/empty params";
        public const string PROJECT_CONFLICTS = "Project conflict(s)";
        public const string ALREADY_IMPORTED = "Already imported";
        public const string IMPORTED = "Imported";
        public const string SUBPROJECTS_LIST_TO_IMPORT_SHOULD_NOT_BE_NULL = "Subprojects list to import should not be null";
        public const string SUBPROJECTS_LIST_TO_IMPORT_SHOULD_BE_FILLED = "Subprojects list to import should contain at least 1 subproject";
        public const string SUBPROJECTS_CONFLICTS = "Subprojects conflict(s)";
    }
}
