namespace NewsFeedSystem.Core
{
    public class ErrorStrings
    {
        public const string OK = "OK";
        
        //AuthUser
        public const string EMPTY_OR_NULL_PASSWORD_HASH = "Empty/null/space password hash";
        public const string GRANTER_NOT_FOUND = "granter not found";
        public const string USER_NOT_FOUND = "User not found";
        public const string PASSWORD_HASH_MISMATCH = "Password(hash) mismatch";
        public const string USER_UPDATED = "User updated";
        public const string USER_IS_ACTUAL = "User is actual";
        public const string LOGIN_MISMATCH = "Login mismatch";
        public const string GRANTERLOGIN_MISMATCH = "GranterLogin mismatch";

        public const string AUTHUSER_PARAM_NAME = "authUser";
        public const string USER_ID_SHOULD_BE_ZERO = "Id in Register request should be zero (generated by DB)";
        public const string LOGIN_SHOULD_NOT_BE_EMPTY = "Login should be not empty";
        public const string USERNAME_SHOULD_NOT_BE_EMPTY = "UserName should be not empty";
        public const string EMAIL_SHOULD_NOT_BE_EMPTY = "Email should be not empty";
        public const string PASSWORD_HASH_SHOULD_NOT_BE_EMPTY = "Passwordhash should be not empty";
        public const string LOGINDATA_PARAM_NAME = "loginData";
        public const string GRANTROLEDATA_PARAM_NAME = "grantRoleData";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY = "GranterLogin should be not empty";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY_DELETE = "GranterLogin should be not empty when GranterId is not null";
        public const string GRANTERLOGIN_SHOULD_BE_EMPTY_DELETE = "GranterLogin should be empty when GranterId is null";
        public const string UPDATEACCOUNTDATA_PARAM_NAME = "updateAccountData";
        public const string DELETEACCOUNTDATA_PARAM_NAME = "deleteAccountData";
        public const string CONFLICT = "Conflict with existing AuthUser";
        public const string ALREADY_EXISTS = "AuthUser is already existing";
        
        //News
        public const string NEWSPOST_RARAM_NAME = "newsPost";
        public const string HEADLINE_SHOULD_NOT_BE_EMPTY = "Headline field should be not empty";
        public const string TEXT_SHOULD_NOT_BE_EMPTY = "Text field should be not empty";
        public const string TAGS_SHOULD_NOT_BE_NULL_OR_EMPTY = "Tags list should be not be null or empty";
        public const string TOPICS_SHOULD_NOT_BE_NULL_OR_EMPTY = "Topics list should be not be null or empty";
        public const string NEWS_NOT_FOUND = "News post not found";
        public const string NEWS_UPDATED = "News post updated";
        public const string NEWS_IS_ACTUAL = "News post is actual";

        //Tags
        public const string TAG_RARAM_NAME = "tag";
        public const string TAG_NAME_SHOULD_NOT_BE_EMPTY = "Tag.Name field should be not empty";
        public const string TAG_UPDATED = "Tag updated";
        public const string TAG_IS_ACTUAL = "Tag is actual";

        //Topics
        public const string TOPIC_RARAM_NAME = "topic";
        public const string TOPIC_NAME_SHOULD_NOT_BE_EMPTY = "Topic.Name field should be not empty";
        public const string TOPIC_NOT_FOUND = "Topic not found";
        public const string TOPIC_UPDATED = "Topic updated";
        public const string TOPIC_IS_ACTUAL = "Topic is actual";
    }
}
