namespace LiteAuthService.Core
{
    public class ErrorStrings
    {
        public const string EMPTY_OR_NULL_PASSWORD_HASH = "Empty/null/space password hash";
        public const string GRANTER_NOT_FOUND = "granter not found";
        public const string USER_NOT_FOUND = "User not found";
        public const string PASSWORD_HASH_MISMATCH = "Password(hash) mismatch";
        public const string USER_UPDATED = "User updated";
        public const string USER_IS_ACTUAL = "User is actual";
        public const string LOGIN_MISMATCH = "Login mismatch";
        public const string GRANTERLOGIN_MISMATCH = "GranterLogin mismatch";

        public const string AUTHUSER_PARAM_NAME = "authUser";
        public const string USER_ID_SHOULD_BE_ZERO = "Id in Register request should be zero (generated by DB)";
        public const string LOGIN_SHOULD_NOT_BE_EMPTY = "Login should be not empty";
        public const string USERNAME_SHOULD_NOT_BE_EMPTY = "UserName should be not empty";
        public const string EMAIL_SHOULD_NOT_BE_EMPTY = "Email should be not empty";
        public const string PASSWORD_HASH_SHOULD_NOT_BE_EMPTY = "Passwordhash should be not empty";
        public const string LOGINDATA_PARAM_NAME = "loginData";
        public const string GRANTROLEDATA_PARAM_NAME = "grantRoleData";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY = "GranterLogin should be not empty";
        public const string GRANTERLOGIN_SHOULD_NOT_BE_EMPTY_DELETE = "GranterLogin should be not empty when GranterId is not null";
        public const string GRANTERLOGIN_SHOULD_BE_EMPTY_DELETE = "GranterLogin should be empty when GranterId is null";
        public const string UPDATEACCOUNTDATA_PARAM_NAME = "updateAccountData";
        public const string DELETEACCOUNTDATA_PARAM_NAME = "deleteAccountData";
        public const string AFFECTED_DELETED_ROWS_COUNT_SHOULD_BE_ONE = "Affected(deleted) rows count should be equal 1.Affected:";
        public const string AFFECTED_UPDATED_ROWS_COUNT_SHOULD_BE_ONE = "Affected(updated) rows count should be equal 1.Affected:";
        public const string OK = "OK";
    }
}
