@ProjectTasksTrackService.API_HostAddress = https://localhost:7120

POST {{ProjectTasksTrackService.API_HostAddress}}/Project/create
Content-Type: application/json

{
    "id":0,
    "name":"new project"
}

###
