@ProjectTasksTrackService.API_HostAddress = https://localhost:7120/ProjectTasksTrackService

POST {{ProjectTasksTrackService.API_HostAddress}}/api/v2/Projects/Create
Content-Type: application/json

{
    "id":0,
    "name":"new project"
}

###
